# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Book2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!  
  # Your 'node_modules' directory is probably in the root of your project,
  # but if not, adjust the `:path` accordingly
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47 
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43 
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging 
    # Add any other subspecs you want to use in your project
    'RCTImage', 
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0 
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
 
  # Third party deps podspec link 
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'

  # Pods for Book2

  # pod 'RNGL', :path => '../node_modules/gl-react-native'

  # pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'

  pod 'Picker', :path => '../node_modules/react-native-picker'

  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  # pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  # pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end